# Generated by Django 6.0.6 on 2026-06-09 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_annonce', models.CharField(choices=[('OFFRE', 'Offre de mentorat'), ('DEMANDE', 'Demande de mentorat')], max_length=10)),
                ('matiere', models.CharField(max_length=100)),
                ('format_cours', models.CharField(choices=[('EN_LIGNE', 'En ligne'), ('PRESENTIEL', 'Présentiel')], max_length=15)),
                ('disponibilites', models.CharField(help_text='Ex: Samedi matin, Jeudi soir', max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(help_text='Ex: Génie Logiciel, IA...', max_length=100)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=2)),
                ('competences', models.TextField(help_text='Matières maîtrisées (séparées par des virgules)')),
                ('lacunes', models.TextField(help_text="Matières où l'étudiant a besoin d'aide")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='profiles.annonce')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_candidatures', to='profiles.profil')),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profil'),
        ),
    ]
