# Generated by Django 6.0.6 on 2026-06-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
